-- Project on Retailer Sales

-- 1. Retrieve all columns from the `products` table.
SELECT *
FROM products;

-- 2. Retrieve only the `product_id` and `Product` columns from the `products` table.
SELECT product_id, Product 
FROM products;

-- 3. Retrieve the `Customer name` and `city` from the `customers` table.
SELECT Customer_Name, city 
FROM customers;

SELECT COUNT(*) AS total_customers
FROM customers;

SELECT COUNT(DISTINCT customer_id) AS total_customers_with_orders
FROM orders ;

SELECT COUNT(*) AS customers_without_orders
FROM customers c
WHERE c.customer_id NOT IN (
    SELECT DISTINCT o.customer_id
    FROM orders o
);


-- 4. Write a query to display all columns from the `orders` table.
SELECT * 
FROM orders;

-- Total order
SELECT COUNT(*) AS total_orders 
FROM orders;

SELECT 
    SUM(quantity * unit_price) AS total_revenue
FROM 
    order_items AS oi;




-- 5. Display the `order_id`, `order_date`, and `total_amount` from the `orders` table.
SELECT order_id, order_date, total_amount 
FROM orders;


-- 6. Retrieve all products from the `products` table where the `price` is greater than 500.
SELECT * 
FROM products 
WHERE price > 500;

-- 7. Find all customers from the `customers` table who live in "Houston".
SELECT * 
FROM customers 
WHERE city = 'Houston';

-- 8. Retrieve all orders from the `orders` table where the `total_amount` is less than 1000.
SELECT * 
FROM orders 
WHERE total_amount < 1000;

-- 9. Find all products in the `products` table that belong to the "Electronics" category.
SELECT * 
FROM products 
WHERE category = 'Electronics';

-- 10. Count the number of products in each category from the `products` table and group the results by `Category`.
SELECT Category, COUNT(*) as total_products
FROM products
GROUP BY Category;

-- 11. Retrieve the total number of orders placed by each customer from the `orders` table, grouped by `customer_id`.
SELECT customer_id, COUNT(*) as total_orders
FROM orders
GROUP BY customer_id;

-- 12. Display the average `price` of products in each category, sorted by the average price in descending order.
SELECT Category, Round(AVG(price),2) as average_price
FROM products
GROUP BY Category
ORDER BY average_price DESC;

-- 13. Find the total `quantity` of each product sold from the `order_items` table, grouped by `product_id`.
SELECT product_id, SUM(quantity) as total_quantity
FROM order_items
GROUP BY product_id;

-- 14. Retrieve categories from the `products` table where the average price is greater than 500 (use `GROUP BY` and `HAVING`).
SELECT Category, ROUND(AVG(price),2) as average_price
FROM products
GROUP BY Category
HAVING average_price > 500;

-- 15. Find customers from the `customers` table who are in the "Young" age bracket (use `WHERE`).
SELECT *
FROM  customers
WHERE age BETWEEN 18 AND 31;


-- 16. Retrieve products from the `products` table where the price is greater than 300 and the category is "Accessories" (use `WHERE`).
SELECT *
FROM products
WHERE price > 300 AND Category = 'Accessories';

-- 17. Display categories from the `products` table that have more than 5 products (use `GROUP BY` and `HAVING`)
SELECT Category, COUNT(*) as total_products
FROM products
GROUP BY Category
HAVING total_products > 5;


-- 18. Retrieve the top 5 most expensive products from the `products` table (use `LIMIT`).
SELECT *
FROM products
ORDER BY price DESC
LIMIT 5;

-- 19. Display the first 10 orders from the `orders` table, sorted by `order_date` in ascending order.
SELECT *
FROM orders
ORDER BY order_date ASC
LIMIT 10;

-- 20. Retrieve the `product_id` and `Product` from the `products` table, and alias them as `ID` and `Product Name`.
SELECT product_id AS ID, Product AS `Product Name`
FROM products;

-- 21. Find the top 3 customers with the highest `total_amount` spent from the `orders` table.
SELECT customer_id, ROUND(SUM(total_amount),2) AS total_spent
FROM orders
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 3;

SELECT *
FROM customers;

SELECT *
FROM order_items;

-- 22. Retrieve the `order_id`, `order_date`, and `Customer name` by joining the `orders` and `customers` tables.
SELECT order_id, order_date,`Customer_name`
FROM orders AS o
INNER JOIN customers AS C 
ON o.customer_id = c.customer_id;

-- Average order of the products
SELECT 
    COUNT(DISTINCT o.order_id) AS avg_order_value
FROM 
    orders AS o
JOIN 
    order_items AS oi ON o.order_id = oi.order_id
JOIN 
    products AS p ON oi.product_id = p.product_id;


-- 23. Display the `product_id`, `Product`, and `quantity` sold by joining the `products` and `order_items` tables.
SELECT p.Product_id, Product, Quantity
FROM products AS p
INNER JOIN order_items AS oi
ON p.product_id = oi.product_id;


-- 24. Find the total revenue generated by each product by joining the `products` and `order_items` tables.
SELECT p.product_id, Product, ROUND(SUM(oi.quantity * p.price),2) AS total_revenue
FROM products AS p
INNER JOIN order_items AS oi 
ON p.product_id = oi.product_id
GROUP BY p.product_id, Product;

-- 25. Retrieve the `Customer name`, `order_date`, and `total_amount` by joining the `customers` and `orders` tables.
SELECT Customer_Name, Order_date, Total_amount
FROM customers AS c
INNER JOIN orders AS o 
ON c.customer_id = o.customer_id;

-- 26. Retrieve a list of all unique cities from the `customers` table and combine it with a list of all unique categories from the `products` table (use `UNION`).
SELECT city AS unique_values
FROM customers
UNION
SELECT Category
FROM products;

-- 27. Combine the `product_id` from the `products` table with the `order_id` from the `orders` table (use `UNION`).
SELECT product_id AS ids
FROM products
UNION
SELECT order_i
FROM orders;

-- 28. Create a new column in the `products` table called `Price Range` that categorizes products as "Low" (price < 300), "Medium" (price between 300 and 700), and "High" (price > 700) using a `CASE` statement.
SELECT *,
CASE WHEN price < 300 THEN 'Low' WHEN price BETWEEN 300 AND 700 THEN 'Medium' ELSE 'High' END AS `Price Range`
FROM products;

SELECT 
    CASE 
        WHEN price < 300 THEN 'Low'
        WHEN price BETWEEN 300 AND 700 THEN 'Medium'
        WHEN price > 700 THEN 'High'
    END AS Price_Range,
    COUNT(*) AS total_products,
    CONCAT(ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM products), 2), '%') AS percentage
FROM 
    products
GROUP BY 
    Price_Range
ORDER BY 
    total_products DESC;


-- 29. Use a `CASE` statement to categorize customers in the `customers` table as "Young" (age <= 33), "Working Class" (age between 34 and 49), and "Retired" (age >= 50).
SELECT *,
CASE WHEN age <= 33 THEN 'Young' WHEN age BETWEEN 34 AND 49 THEN 'Working Class' ELSE 'Retired' END AS age_category
FROM customers;

SELECT 
    CASE 
        WHEN age <= 33 THEN 'Young'
        WHEN age BETWEEN 34 AND 49 THEN 'Working Class'
        ELSE 'Retired'
    END AS Age_Bracket, COUNT(*) AS total_customers,
    ROUND((COUNT(*) / (SELECT COUNT(*) FROM customers)) * 100, 2
    ) AS percent_customers
FROM customers
GROUP BY Age_Bracket
ORDER BY total_customers DESC;


-- 30. Retrieve the `order_id` and a new column called `Order Size` that categorizes orders as "Small" (total_amount < 500), "Medium" (total_amount between 500 and 1000), and "Large" (total_amount > 1000) using a `CASE` statement.
SELECT order_id,
CASE WHEN total_amount < 500 THEN 'Small' WHEN total_amount BETWEEN 500 AND 1000 THEN 'Medium' ELSE 'Large' END AS `Order Size`
FROM orders;

SELECT 
    CASE 
        WHEN total_amount < 500 THEN 'Small'
        WHEN total_amount BETWEEN 500 AND 1000 THEN 'Medium'
        WHEN total_amount > 1000 THEN 'Large'
    END AS Order_Size,
    COUNT(*) AS total_orders,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM orders), 2) AS percentage
FROM 
    orders
GROUP BY 
    Order_Size
ORDER BY 
    total_orders DESC;



-- 31. Find the top 5 customers who have spent the most money in total (join `customers` and `orders` tables).
SELECT Customer_name, CONCAT('$', FORMAT(SUM(Total_amount), 2)) AS Total_spent
FROM customers AS c
INNER JOIN orders AS o ON c.customer_id = o.customer_id
GROUP BY Customer_name
ORDER BY SUM(Total_amount) DESC
LIMIT 5;


-- 32. Retrieve the `Product` name, `Category`, and total revenue generated by each product (join `products` and `order_items` tables).
SELECT Product, Category, ROUND(SUM(Quantity * Price),2) AS Total_revenue
FROM products AS p
INNER JOIN order_items AS oi 
ON p.product_id = oi.product_id
GROUP BY Product, Category;

SELECT Product, Category,
    SUM(quantity * unit_price) AS total_revenue,
    ROUND(SUM(quantity * unit_price) * 100.0 / 
          (SELECT SUM(quantity * unit_price) FROM order_items), 2) AS percentage
FROM 
    products AS p
JOIN 
    order_items AS oi ON p.product_id = oi.product_id
GROUP BY 
    product, category
ORDER BY 
    total_revenue DESC;
    
    SELECT Category,
    SUM(quantity * unit_price) AS total_revenue,
    ROUND(SUM(quantity * unit_price) * 100.0 / 
          (SELECT SUM(quantity * unit_price) FROM order_items), 2) AS percentage
FROM 
    products AS p
JOIN 
    order_items AS oi ON p.product_id = oi.product_id
GROUP BY 
    category
ORDER BY 
    total_revenue DESC;



-- Accumulative of the total revenue in currency 
SELECT 
   CONCAT('$', FORMAT(SUM(quantity * price), 0)) AS total_revenue
FROM 
    order_items AS oi
JOIN 
    products p ON oi.product_id = p.product_id;


-- 33. Display the `Customer name`, `order_date`, and `total_amount` for orders placed in January 2023 (use `WHERE` with date filtering).
SELECT Customer_name, order_date, Total_amount
FROM customers AS c
INNER JOIN orders AS o 
ON c.customer_id = o.customer_id
WHERE order_date BETWEEN '2023-01-01' AND '2023-01-31';


-- 34. Find the average `total_amount` of orders for each customer, and display only those customers whose average order amount is greater than 1000 (use `GROUP BY` and `HAVING`).
SELECT Customer_name, ROUND(AVG(Total_amount),2) AS average_order
FROM customers AS c
INNER JOIN orders AS o 
ON c.customer_id = o.customer_id
GROUP BY Customer_name
HAVING average_order > 1000;

-- 35. Retrieve the `Customer name`, `Product`, and `quantity` for all orders placed by customers in "New York" (join `customers`, `orders`, and `order_items` tables).
SELECT Customer_name, Product, Quantity
FROM customers AS c
INNER JOIN orders o 
ON c.customer_id = o.customer_id
INNER JOIN order_items AS oi 
ON o.order_id = oi.order_id
INNER JOIN products AS p 
ON oi.product_id = p.product_id
WHERE c.city = 'New York';

-- Top city buyer
SELECT 
    city,
    COUNT(DISTINCT order_id) AS total_orders
FROM 
    orders AS o
JOIN 
    customers  AS c ON o.customer_id = c.customer_id
GROUP BY 
    city
ORDER BY 
    total_orders DESC
LIMIT 1;





-- 36. Find customers who placed orders in both January and February 2023.
SELECT Customer_Name
FROM customers AS c
INNER JOIN orders AS o 
ON c.customer_id = o.customer_id
WHERE order_date BETWEEN '2023-01-01' AND '2023-02-28'
GROUP BY Customer_name
HAVING COUNT(DISTINCT MONTH(o.order_date)) = 2;

-- Monthly Revenue
SELECT 
    MONTHNAME(o.order_date) AS month,
    CONCAT('$', FORMAT(SUM(o.Total_amount), 2)) AS monthly_revenue
FROM 
    orders o
WHERE 
    YEAR(o.order_date) = 2023
GROUP BY 
    MONTH(o.order_date), MONTHNAME(o.order_date)
ORDER BY 
    MONTH(o.order_date);
    
   



 
  




